# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Tue Jul  5 00:28:38 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from dimview import DimView

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.dimscapeView = DimView(self.centralwidget)
        self.dimscapeView.setObjectName(_fromUtf8("dimscapeView"))
        self.verticalLayout.addWidget(self.dimscapeView)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setAccessibleName(_fromUtf8(""))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuDimension = QtGui.QMenu(self.menubar)
        self.menuDimension.setObjectName(_fromUtf8("menuDimension"))
        self.menuCell = QtGui.QMenu(self.menubar)
        self.menuCell.setObjectName(_fromUtf8("menuCell"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Space = QtGui.QAction(MainWindow)
        self.actionNew_Space.setObjectName(_fromUtf8("actionNew_Space"))
        self.actionLoad_Space = QtGui.QAction(MainWindow)
        self.actionLoad_Space.setObjectName(_fromUtf8("actionLoad_Space"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionX = QtGui.QAction(MainWindow)
        self.actionX.setObjectName(_fromUtf8("actionX"))
        self.actionY = QtGui.QAction(MainWindow)
        self.actionY.setObjectName(_fromUtf8("actionY"))
        self.actionZ = QtGui.QAction(MainWindow)
        self.actionZ.setObjectName(_fromUtf8("actionZ"))
        self.actionEdit_Cell = QtGui.QAction(MainWindow)
        self.actionEdit_Cell.setObjectName(_fromUtf8("actionEdit_Cell"))
        self.actionInsert_Cell = QtGui.QAction(MainWindow)
        self.actionInsert_Cell.setObjectName(_fromUtf8("actionInsert_Cell"))
        self.actionDelete_Cell = QtGui.QAction(MainWindow)
        self.actionDelete_Cell.setObjectName(_fromUtf8("actionDelete_Cell"))
        self.actionSave_Space = QtGui.QAction(MainWindow)
        self.actionSave_Space.setObjectName(_fromUtf8("actionSave_Space"))
        self.actionSave_Space_As = QtGui.QAction(MainWindow)
        self.actionSave_Space_As.setObjectName(_fromUtf8("actionSave_Space_As"))
        self.actionNew_Dim = QtGui.QAction(MainWindow)
        self.actionNew_Dim.setObjectName(_fromUtf8("actionNew_Dim"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuFile.addAction(self.actionNew_Space)
        self.menuFile.addAction(self.actionLoad_Space)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Space)
        self.menuFile.addAction(self.actionSave_Space_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuDimension.addAction(self.actionNew_Dim)
        self.menuCell.addAction(self.actionEdit_Cell)
        self.menuCell.addAction(self.actionInsert_Cell)
        self.menuCell.addAction(self.actionDelete_Cell)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDimension.menuAction())
        self.menubar.addAction(self.menuCell.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Dimscape", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDimension.setTitle(QtGui.QApplication.translate("MainWindow", "&Dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCell.setTitle(QtGui.QApplication.translate("MainWindow", "&Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Space.setText(QtGui.QApplication.translate("MainWindow", "&New Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Space.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Space.setText(QtGui.QApplication.translate("MainWindow", "&Open Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Space.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionY.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZ.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_Cell.setText(QtGui.QApplication.translate("MainWindow", "Edit Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsert_Cell.setText(QtGui.QApplication.translate("MainWindow", "Insert Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Cell.setText(QtGui.QApplication.translate("MainWindow", "Delete Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Space.setText(QtGui.QApplication.translate("MainWindow", "&Save Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Space.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Space_As.setText(QtGui.QApplication.translate("MainWindow", "Save Space &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Dim.setText(QtGui.QApplication.translate("MainWindow", "New Dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Dim.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

